# Learning Python for Data Analysis and Visualization

In [34]:
import numpy as np

## Python list covert to numpy array

In [21]:
list1 = [1,2,3,4]

In [8]:
np_arr1 = np.array(list1)
np_arr1

array([1, 2, 3, 4])

In [9]:
list2 = [11,22,33,44]

## Multi-dimensional numpy array create

In [11]:
list3 = [list1, list2]
list3

[[1, 2, 3, 4], [11, 22, 33, 44]]

In [13]:
np_arr2 = np.array(list3)
np_arr2

array([[ 1,  2,  3,  4],
       [11, 22, 33, 44]])

## Good to know functions

In [15]:
np_arr2.shape

(2L, 4L)

In [17]:
np_arr2.dtype

dtype('int32')

In [25]:
# np.zeros, np.empty, mp.ones are working similar way
np_zero_arr = np.zeros(5)
np_zero_arr

array([ 0.,  0.,  0.,  0.,  0.])

In [27]:
np_zero_arr.dtype

dtype('float64')

In [29]:
np.zeros([5, 5])

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]])

In [32]:
# identity matrix
np.eye(5)

array([[ 1.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  1.]])

In [38]:
# arrange(x) arange(o) think about a - range
np.arange(5, 50, 2)

array([ 5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35, 37,
       39, 41, 43, 45, 47, 49])