# Indexing

In [1]:
import numpy as np

In [4]:
arr = np.arange(0, 11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [7]:
arr[3] # 0 base index

3

In [9]:
arr[0:5] #[inclusive:exclusive]

array([0, 1, 2, 3, 4])

In [11]:
arr[0:3] = 1000
arr

array([1000, 1000, 1000,    3,    4,    5,    6,    7,    8,    9,   10])

## Slice

In [14]:
sarr1 = arr[0:6]
sarr1

array([1000, 1000, 1000,    3,    4,    5])

In [17]:
sarr1[0] = 0
sarr1

array([   0, 1000, 1000,    3,    4,    5])

In [19]:
arr

array([   0, 1000, 1000,    3,    4,    5,    6,    7,    8,    9,   10])

In [22]:
arr_copy = arr[0:5].copy()
arr_copy

array([   0, 1000, 1000,    3,    4])

In [23]:
arr_copy[1] = 1
arr_copy

array([   0,    1, 1000,    3,    4])

In [24]:
arr

array([   0, 1000, 1000,    3,    4,    5,    6,    7,    8,    9,   10])

In [ ]:
 ## M

In [39]:
arr_2d = np.array([[3,6,9],[12,15,18],[21,24,27]])

In [40]:
arr_2d

array([[ 3,  6,  9],
       [12, 15, 18],
       [21, 24, 27]])

In [41]:
arr_2d[1][1]

15

In [48]:
arr_2d[0:2,0:2]

array([[ 3,  6],
       [12, 15]])

In [50]:
arr_2d[[0,2]]

array([[ 3,  6,  9],
       [21, 24, 27]])

In [44]:
arr_2d.shape

(3, 3)

In [47]:
arr_2d.shape[0]

3