# Element-level operation (scalar)

In [3]:
import numpy as np

In [4]:
arr1 = [[1,2,3,4], [5,6,7,8]]

In [10]:
np_arr1 = np.array(arr1)

In [12]:
np_arr1 + 5

array([[ 6,  7,  8,  9],
       [10, 11, 12, 13]])

In [13]:
np_arr1 - 3

array([[-2, -1,  0,  1],
       [ 2,  3,  4,  5]])

In [14]:
np_arr1 * 2

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16]])

In [15]:
np_arr1 / 2

array([[ 0.5,  1. ,  1.5,  2. ],
       [ 2.5,  3. ,  3.5,  4. ]])

In [18]:
np_arr1 ** 3

array([[  1,   8,  27,  64],
       [125, 216, 343, 512]], dtype=int32)

In [19]:
1 / np_arr1

array([[ 1.        ,  0.5       ,  0.33333333,  0.25      ],
       [ 0.2       ,  0.16666667,  0.14285714,  0.125     ]])